// Константы для кораблей
const SET_STARSHIPS = 'SET_STARSHIPS'
const SET_STARSHIP = 'SET_STARSHIP'

const ERROR_STARSHIPS = 'ERROR_STARSHIPS'
const ERROR_STARSHIP = 'ERROR_STARSHIP'

export {
    SET_STARSHIPS,
    SET_STARSHIP,
    ERROR_STARSHIPS,
    ERROR_STARSHIP
}