// Константы для планет
const SET_PLANETS = 'SET_PLANETS'
const SET_PLANET = 'SET_PLANET'
const SET_RANDOM_PLANET = 'SET_RANDOM_PLANET'

const ERROR_PLANETS = 'ERROR_PLANETS'
const ERROR_PLANET = 'ERROR_PLANET'

export {
    SET_PLANETS,
    SET_PLANET,
    SET_RANDOM_PLANET,
    ERROR_PLANETS,
    ERROR_PLANET
}